version: "3.9"
services:
  web:
    build: .
    container_name: devgis_web
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-change-this-in-prod}
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://devgis:devgis@db:5432/devgis
    depends_on:
      - db
    volumes:
      - ./:/app
  db:
    image: postgres:16-alpine
    container_name: devgis_db
    environment:
      POSTGRES_DB: devgis
      POSTGRES_USER: devgis
      POSTGRES_PASSWORD: devgis
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
